name:  Action Item
description: Action Item submission
title: "[Action Item]"
labels: ["Action Item"]
projects: ["Add project"]
assignees: 
- mvaltas
- chrisxie-fw
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Outline Action Item Details
      description: Outline Action Item Details
      placeholder: Tell us what you see
      value: "Add details"
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other WGs Groups
      multiple: true
      options:
        - No Dependency
        - Community WG
        - Opensource WG
        - Policy WG
