name:  Documentation
description: Issue associated with Documentation
title: "[Documentation]"
labels: ["documentation"]
projects: ["Add project"]
assignees: 
- mvaltas
- chrisxie-fw
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Outline Action Item Details
      description: Outline Action Item Details
      placeholder: Tell us what you see
      value: "Add details for proposed changes or additions"
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other WG Groups
      multiple: true
      options:
        - No Dependency
        - Community WG
        - Opensource WG
        - Policy WG
